/**
 * Combined design rows from data/*.json (adder, voter, cordic).
 * AUTO-GENERATED by scripts/generate-design-data.mjs. Run: npm run generate:data
 * Do not edit by hand; edit the JSON files in /data instead.
 */

import type { DesignRow } from "./designTypes";

export const DESIGN_ROWS: DesignRow[] = [
  { architecture: "rca", bitWidth: 32, fmaxMhz: 420, powerMw: 2.1, areaUm2: 2100, designFamily: "adder" },
  { architecture: "rca", bitWidth: 64, fmaxMhz: 310, powerMw: 3.8, areaUm2: 4100, designFamily: "adder" },
  { architecture: "cla", bitWidth: 32, fmaxMhz: 680, powerMw: 3.2, areaUm2: 3400, designFamily: "adder" },
  { architecture: "cla", bitWidth: 64, fmaxMhz: 520, powerMw: 5.9, areaUm2: 6500, designFamily: "adder" },
  { architecture: "kogge_stone", bitWidth: 32, fmaxMhz: 920, powerMw: 4.8, areaUm2: 5200, designFamily: "voter" },
  { architecture: "kogge_stone", bitWidth: 64, fmaxMhz: 780, powerMw: 8.4, areaUm2: 9800, designFamily: "voter" },
  { architecture: "brent_kung", bitWidth: 32, fmaxMhz: 850, powerMw: 4.1, areaUm2: 4800, designFamily: "cordic" },
  { architecture: "brent_kung", bitWidth: 64, fmaxMhz: 710, powerMw: 7.2, areaUm2: 9100, designFamily: "cordic" }
];
